language: cpp

compiler:
    - gcc

before_script:
    # create a build folder for out-of-source build
    - mkdir build
    # switch to build directory
    - cd build
    # run cmake; here we assume that the project's
    # top-level CMakeLists.txt is located at '..'
    - cmake ..

script:
    - cmake --build .
    - cmake --build . --target test
    - cmake --build . --target package
    